//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audio_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int id { get; set; }
        public string link { get; set; }
        public string song_name { get; set; }
        public int artist_id { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
